on:
  pull_request:
  workflow_dispatch:

# this cancels workflows currently in progress if you start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test-nix:
    strategy:
      fail-fast: false
      matrix:
        # macos-12 uses x86-64 machine, macos-14 uses aarch64
        os: [macos-12, macos-14, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      # install nix
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          
      - name: Run all tests
        run: nix develop -c sh -c 'export ROC=roc && export EXAMPLES_DIR=./examples/ && ./ci/all_tests.sh'

      - name: build example in README.md
        run: |
          roc_block_count=$(grep -c '```roc' README.md)
          
          # Error if more than one Roc code block
          if [ $roc_block_count -gt 1 ]; then
            echo "Error: Found $roc_block_count Roc code blocks in README.md. I only know how to test one. Modify this CI step to test them all."
            exit 1
          fi

          # Extract roc code block from README.md
          sed -n '/```roc/,/```/p' README.md | sed '1d;$d' > readme.roc

          # Build the code to make sure it works
          roc build readme.roc --linker=legacy
